server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://122.51.97.52:33306/ruan
    username: root
    password: polestar
  application:
    name: service-provider
mybatis:
  type-aliases-package: com.ruan.service.pojo
logging:
  level:
    com.ruan: debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka