spring:
  redis:
    database: 1
    host: ${REDIS_HOST:122.51.97.52}
    port: ${REDIS_PORT:9533}
    password: polestar
  application:
    name: ruan-mq
  rabbitmq:
    host: 122.51.97.52
    port: 5672
    virtual-host: /
    username: polestar
    password: ruan
    publisher-confirms: true
    publisher-returns: true
    # 手动ack配置
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
server:
  port: 9982
