server:
  port: 80


logging:
  level:
    root: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka

service-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # 设置hystrix的超时时间为6000ms

feign:
  hystrix:
    enabled: true
spring:
  application:
    name: service-consumer